# Generated by Django 3.2.4 on 2023-01-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Migrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='migration name')),
                ('content', models.TextField(verbose_name='content')),
                ('app', models.CharField(max_length=32, verbose_name='app name')),
                ('path', models.CharField(max_length=255, verbose_name='migration file path')),
                ('index', models.SmallIntegerField(default=0, verbose_name='index')),
                ('ex_info', models.JSONField(default=dict, verbose_name='ex info')),
            ],
        ),
    ]
