# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-21 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
