# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-23 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20180621_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentregister',
            name='device_code',
            field=models.CharField(default='', max_length=32, verbose_name='设备编码'),
        ),
        migrations.AddField(
            model_name='equipmentregister',
            name='status',
            field=models.CharField(choices=[('normal', '正常'), ('abnormal', '异常')], default='normal', max_length=32, verbose_name='状态'),
        ),
    ]
