# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-23 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_orderreturns_order_sn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='product_status',
            field=models.CharField(choices=[('green', 'normal'), ('yellow', 'replace'), ('red', 'patch')], default='green', max_length=64, verbose_name='设备状态'),
        ),
        migrations.AlterField(
            model_name='orderreturns',
            name='order_sn',
            field=models.CharField(default='', max_length=128, verbose_name='退貨單號'),
        ),
    ]
