# -*- coding: utf-8 -*-

# Generated by Django 1.9.8 on 2018-06-25 09:41

from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_auto_20180623_2129'),
        ('model', '0003_auto_20180623_1931'),
    ]

    operations = [
    ]
