# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-25 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_merge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='product_status',
            new_name='equipment_status',
        ),
    ]
