# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-26 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0012_auto_20180625_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreturns',
            name='channel_name',
            field=models.CharField(default='', max_length=128, verbose_name='渠道名称'),
        ),
        migrations.AddField(
            model_name='orderreturns',
            name='cus_phone',
            field=models.CharField(default='', max_length=128, verbose_name='客戶手機'),
        ),
        migrations.AddField(
            model_name='orderreturns',
            name='customer',
            field=models.CharField(default='', max_length=128, verbose_name='客戶名稱'),
        ),
        migrations.AddField(
            model_name='orderreturns',
            name='goods_name',
            field=models.CharField(default='', max_length=128, verbose_name='商品名稱'),
        ),
        migrations.AddField(
            model_name='orderreturns',
            name='order_sn',
            field=models.CharField(default='', max_length=128, verbose_name='退貨單號'),
        ),
        migrations.AddField(
            model_name='orderreturns',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='商品数量'),
        ),
        migrations.AddField(
            model_name='orderreturns',
            name='servicer',
            field=models.CharField(default='', max_length=128, verbose_name='客服名稱'),
        ),
        migrations.AddField(
            model_name='orderreturns',
            name='shop_name',
            field=models.CharField(default='', max_length=128, verbose_name='店铺名称'),
        ),
        migrations.AddField(
            model_name='orderreturns',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='订单金额'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_status',
            field=models.CharField(choices=[('normal', '正常'), ('replace', '售后机'), ('patch', '补货'), ('rgoods', '注册并退货')], default='normal', max_length=64, verbose_name='设备状态'),
        ),
        migrations.AlterField(
            model_name='orderreturns',
            name='remark',
            field=models.CharField(default='', max_length=128, verbose_name='備註'),
        ),
    ]
