# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-04 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0014_auto_20180702_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentSn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, verbose_name='设备编码')),
                ('last_cal_time', models.DateTimeField(blank=True, max_length=20, null=True, verbose_name='最后统计时间')),
                ('total_amount', models.IntegerField(default=0, verbose_name='交易总额/分')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model.Customer')),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model.Equipment')),
                ('logistics_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model.LogisticsItem')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model.Order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model.Product')),
                ('product_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model.ProductModel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
