# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-04 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0015_equipmentsn'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentregister',
            name='equipment_sn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model.EquipmentSn'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='equipment_sn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model.EquipmentSn'),
        ),
    ]
