# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-04 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0016_auto_20180704_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentsn',
            name='logistics_item',
        ),
        migrations.AddField(
            model_name='equipmentsn',
            name='sn_status',
            field=models.CharField(choices=[('normal', '正常'), ('replace', '售后机'), ('patch', '补货'), ('rgoods', '注册并退货')], default='normal', max_length=64, verbose_name='sn状态'),
        ),
        migrations.AddField(
            model_name='logistics',
            name='equipment_sn_list',
            field=models.TextField(default='[]', verbose_name='sn码列表'),
        ),
    ]
