# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-04 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0017_auto_20180704_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logistics',
            name='equipment_sn_list',
        ),
        migrations.AddField(
            model_name='logisticsitem',
            name='equipment_sn_list',
            field=models.TextField(default='[]', verbose_name='sn码列表'),
        ),
    ]
