# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-05 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0018_auto_20180704_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurestaff',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model.Department'),
        ),
        migrations.AddField(
            model_name='stafforderevent',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model.Department'),
        ),
    ]
