# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-06 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0019_auto_20180705_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model.Equipment'),
        ),
    ]
