# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-09 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0020_auto_20180706_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name = 'mobilephone',
            name = 'department',
            field = models.CharField(default = '', max_length = 128, verbose_name = '部门'),
        ),
        migrations.AddField(
            model_name = 'mobilephone',
            name = 'leader',
            field = models.CharField(default = '', max_length = 64, verbose_name = '负责人'),
        ),
        migrations.AddField(
            model_name = 'mobilephone',
            name = 't_member',
            field = models.CharField(default = '', max_length = 64, verbose_name = '组员'),
        ),
        migrations.AddField(
            model_name = 'role',
            name = 'is_show_all',
            field = models.BooleanField(default = False, verbose_name = '是否展示所有数据(类admin)'),
        ),
        migrations.AlterField(
            model_name = 'journal',
            name = 'journal_type',
            field = models.CharField(choices = [('login', '登录'), ('other', '其它'), ('status reset', '导入数据状态重置'), ('delete', '删除'), ('look', '查詢'), ('edit', '編輯'), ('search', '搜索'), ('remove', '刪除'), ('update', '更新'), ('add', '新增'), ('import', '数据导入')], default = 'other', max_length = 64, verbose_name = '日志类型'),
        ),

    ]
