# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-09 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0021_auto_20180709_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilephone',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model.Department'),
        ),
    ]
