# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-12 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0022_auto_20180709_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentout',
            name='is_agent',
            field=models.BooleanField(default=False, verbose_name='是否为代理商'),
        ),
        migrations.AddField(
            model_name='importequipmentout',
            name='is_agent',
            field=models.CharField(default='否', max_length=32, verbose_name='是否为代理商'),
        ),
        migrations.AddField(
            model_name='trackevent',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model.Department'),
        ),
        migrations.AlterField(
            model_name='stafforderevent',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model.Staff'),
        ),
        migrations.AlterField(
            model_name='trackevent',
            name='remark',
            field=models.TextField(default='', null=True, verbose_name='备注'),
        ),
    ]
