# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-16 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0025_auto_20180713_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffReturnsEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.TextField(default='', null=True, verbose_name='描述')),
                ('remark', models.TextField(verbose_name='备注')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model.Department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='orderreturns',
            old_name='order_sn',
            new_name='returns_num',
        ),
        migrations.RemoveField(
            model_name='orderreturns',
            name='channel_name',
        ),
        migrations.RemoveField(
            model_name='orderreturns',
            name='cus_phone',
        ),
        migrations.RemoveField(
            model_name='orderreturns',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderreturns',
            name='goods_name',
        ),
        migrations.RemoveField(
            model_name='orderreturns',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderreturns',
            name='servicer',
        ),
        migrations.RemoveField(
            model_name='orderreturns',
            name='shop_name',
        ),
        migrations.RemoveField(
            model_name='orderreturns',
            name='total_price',
        ),
        migrations.AddField(
            model_name='orderreturns',
            name='buyinfo_status',
            field=models.CharField(default='red', max_length=64, verbose_name='购买信息状态'),
        ),
        migrations.AddField(
            model_name='orderreturns',
            name='dsinfo_status',
            field=models.CharField(default='red', max_length=64, verbose_name='电刷信息状态'),
        ),
        migrations.AddField(
            model_name='orderreturns',
            name='last_cal_time',
            field=models.DateTimeField(blank=True, max_length=20, null=True, verbose_name='最后统计时间'),
        ),
        migrations.AddField(
            model_name='orderreturns',
            name='rebate_status',
            field=models.CharField(default='red', max_length=64, verbose_name='激活信息状态'),
        ),
        migrations.AddField(
            model_name='orderreturns',
            name='sn_status',
            field=models.CharField(default='red', max_length=64, verbose_name='设备码出入库状态'),
        ),
        migrations.AddField(
            model_name='orderreturns',
            name='total_amount',
            field=models.IntegerField(default=0, verbose_name='交易总额/分'),
        ),
        migrations.AddField(
            model_name='staffreturnsevent',
            name='order_returns',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.OrderReturns'),
        ),
        migrations.AddField(
            model_name='staffreturnsevent',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model.Staff'),
        ),
        migrations.AddField(
            model_name='staffreturnsevent',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Staff'),
        ),
    ]
