# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-16 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0026_auto_20180716_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_security',
            field=models.BooleanField(default=True, verbose_name='是否隐藏关键信息(安全)'),
        ),
    ]
