# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-16 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0027_role_is_security'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='journal_type',
            field=models.CharField(choices=[('login', '登录'), ('other', '其它'), ('status reset', '导入数据状态重置'), ('delete', '删除'), ('look', '查詢'), ('edit', '編輯'), ('search', '搜索'), ('remove', '刪除'), ('update', '更新'), ('add', '新增'), ('import', '数据导入'), ('recover', '恢复')], default='other', max_length=64, verbose_name='日志类型'),
        ),
        migrations.AlterField(
            model_name='staffreturnsevent',
            name='remark',
            field=models.TextField(default='', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='staffreturnsevent',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model.Staff'),
        ),
    ]
