# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-23 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0028_auto_20180716_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('remark', models.TextField(default='', verbose_name='备注')),
                ('status', models.CharField(choices=[('unexecuted', '未执行'), ('executed', '已执行')], default='unexecuted', max_length=32, verbose_name='状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('adder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_adder', to='model.Staff')),
                ('department_front', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_department_front', to='model.Department')),
                ('department_now', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_department_now', to='model.Department')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_executor', to='model.Staff')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_staff', to='model.Staff')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
