# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-25 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0030_auto_20180723_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttransaction',
            name='good_service_fee',
            field=models.IntegerField(default=0, verbose_name='优享手续费/分'),
        ),
        migrations.AddField(
            model_name='equipmenttransaction',
            name='good_service_rate',
            field=models.IntegerField(default=0, verbose_name='优享费率'),
        ),
        migrations.AddField(
            model_name='importcustomertransaction',
            name='good_service_fee',
            field=models.IntegerField(default=0, verbose_name='优享手续费/分'),
        ),
        migrations.AddField(
            model_name='importcustomertransaction',
            name='good_service_rate',
            field=models.IntegerField(default=0, verbose_name='优享费率'),
        ),
    ]
