# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-30 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0031_auto_20180725_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='dsinfo_status',
            field=models.CharField(choices=[('red', '红'), ('yellow', '黄'), ('green', '绿'), ('tgreen', '双绿')], default='red', max_length=64, verbose_name='点刷信息状态'),
        ),
    ]
