# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-30 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0032_auto_20180730_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replenishmentitem',
            name='status',
            field=models.CharField(choices=[('wait', '待补货'), ('export', '已导出'), ('done', '已完成'), ('resend', '补货中')], default='', max_length=64, verbose_name='补货状态'),
        ),
    ]
