# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-09-05 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0033_auto_20180730_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='p_end_time',
            field=models.DateField(blank=True, null=True, verbose_name='保护截止时间'),
        ),
        migrations.AddField(
            model_name='staff',
            name='p_start_time',
            field=models.DateField(blank=True, null=True, verbose_name='保护开始时间'),
        ),
        migrations.AddField(
            model_name='stafforderevent',
            name='is_count',
            field=models.CharField(choices=[('countin', '计算'), ('countout', '不计算')], default='countin', max_length=24, verbose_name='是否计算'),
        ),
    ]
