# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-09-05 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0034_auto_20180905_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='p_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='保护截止时间'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='p_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='保护开始时间'),
        ),
    ]
