# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-09-06 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0035_auto_20180905_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(default='', max_length=128, verbose_name='商户编号')),
                ('merchant_name', models.CharField(default='', max_length=64, verbose_name='商户名称')),
                ('organ_id', models.CharField(default='', max_length=64, verbose_name='机构编号（代理商编号）')),
                ('organ_name', models.CharField(default='', max_length=64, verbose_name='机构名称')),
                ('organ_level', models.CharField(default='', max_length=64, verbose_name='机构等级')),
                ('real_name', models.CharField(default='', max_length=32, verbose_name='真实姓名')),
                ('id_card', models.CharField(default='', max_length=32, verbose_name='身份证号 ')),
                ('phone', models.CharField(default='', max_length=64, null=True, verbose_name='手机号')),
                ('reg_date', models.DateTimeField(blank=True, null=True, verbose_name='注册时间')),
                ('pid', models.CharField(default='', max_length=32, verbose_name='产品编号 ')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MerchantEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(default='', max_length=256, verbose_name='设备硬件序列号')),
                ('terminal_id', models.CharField(default='', max_length=256, verbose_name='终端编号')),
                ('binding_date', models.DateTimeField(blank=True, null=True, verbose_name='绑定时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('equipment_sn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model.EquipmentSn')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Merchant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MerchantTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_sn', models.CharField(default='', max_length=256, verbose_name='商户编号')),
                ('organ_id', models.CharField(default='', max_length=256, verbose_name='机构编号（代理商编号）')),
                ('serial_no', models.CharField(default='', max_length=256, verbose_name='设备硬件系列号')),
                ('terminal_id', models.CharField(default='', max_length=256, verbose_name='终端编号')),
                ('trans_id', models.CharField(default='', max_length=256, verbose_name='交易编号')),
                ('trans_type', models.IntegerField(default=0, verbose_name='交易类型')),
                ('tx_date', models.DateTimeField(blank=True, null=True, verbose_name='交易时间')),
                ('tx_amt', models.IntegerField(default=0, verbose_name='交易金额/分')),
                ('act_amt', models.IntegerField(default=0, verbose_name='实际到账金额/分')),
                ('tx_ref_id', models.CharField(default='', max_length=256, verbose_name='交易参考号')),
                ('order_no', models.CharField(default='', max_length=256, verbose_name='订单号')),
                ('pid', models.CharField(default='', max_length=256, verbose_name='产品编号')),
                ('transaction_status', models.CharField(choices=[('success', '交易成功'), ('fail', '交易失败')], default='success', max_length=64, verbose_name='交易状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('Merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Merchant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
