# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-09-06 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0036_merchant_merchantequipment_merchanttransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchanttransaction',
            old_name='Merchant',
            new_name='merchant',
        ),
    ]
