# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-09-07 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0037_auto_20180906_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='is_activation',
            field=models.IntegerField(default=0, verbose_name='是否激活 '),
        ),
        migrations.AddField(
            model_name='merchant',
            name='source',
            field=models.CharField(choices=[('ysb', '银收宝'), ('other', '其它')], default='other', max_length=32, verbose_name='商户来源'),
        ),
    ]
