# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-09-09 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0038_auto_20180907_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='authaccess',
            name='is_main',
            field=models.CharField(choices=[('yes', '是'), ('no', '否')], default='yes', max_length=128, verbose_name='是否为主部门'),
        ),
    ]
