# Generated by Django 3.2.4 on 2022-12-13 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyShit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('name', models.CharField(max_length=32, verbose_name='where the money is')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='how many here is')),
                ('invest_type', models.SmallIntegerField(choices=[(0, 'saving'), (1, 'current_deposit'), (2, 'fixed_deposit'), (3, 'steady'), (4, 'found'), (5, 'stocks')], default=0, verbose_name='invest type')),
                ('net_worth', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='net_worth')),
                ('status', models.SmallIntegerField(choices=[(0, 'sell out'), (1, 'buy in'), (2, 'hold')], default=2, verbose_name='status')),
                ('app', models.SmallIntegerField(choices=[(0, 'alipay'), (1, 'wechat'), (2, 'invest bank')], default=2, verbose_name='money app')),
                ('ex_info', models.JSONField(default=dict, verbose_name='ex_info')),
                ('remark', models.CharField(max_length=128, verbose_name='remark')),
            ],
            options={
                'db_table': 'awesomeDong_my_shit',
                'ordering': ('-create_time',),
            },
        ),
    ]
