# Generated by Django 3.2.4 on 2022-12-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_dong', '0001_myshit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myshit',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'sell out'), (1, 'buy in'), (2, 'hold'), (3, 'on the way')], default=2, verbose_name='status'),
        ),
    ]
