# Generated by Django 3.2.4 on 2023-02-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_dong', '0001_squashed_0007_myshit_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myshit',
            name='name',
            field=models.CharField(max_length=64, verbose_name='where the money is'),
        ),
    ]
