# Generated by Django 3.2.4 on 2023-01-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_dong', '0003_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='myshit',
            name='delta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='delta'),
        ),
    ]
