# Generated by Django 3.2.4 on 2023-01-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_dong', '0005_alter_myshit_invest_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myshit',
            name='invest_type',
            field=models.SmallIntegerField(choices=[(0, 'saving'), (1, 'current_deposit'), (2, 'fixed_deposit'), (3, 'steady'), (4, 'monetary fund'), (5, 'bond fund'), (6, 'mixed fund'), (7, 'equity fund'), (8, 'stocks')], default=0, verbose_name='invest type'),
        ),
    ]
