# Generated by Django 2.1.1 on 2019-06-12 04:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beauty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='LittleBoot', max_length=33)),
                ('skin', models.CharField(choices=[('Yellow', '黄色'), ('LightYellow', '浅黄'), ('White', '白皙'), ('LightBlack', '浅黑')], default='Yellow', max_length=13)),
                ('age', models.IntegerField(default=0)),
                ('region', models.CharField(choices=[('Asia', '亚洲'), ('European', '欧洲'), ('USA', '美洲')], default='Asia', max_length=33)),
                ('country', models.CharField(default='Japan', max_length=66)),
                ('height', models.CharField(default='0', max_length=3)),
                ('shape', models.CharField(default='Unknown', max_length=50)),
                ('bra', models.CharField(default='B', max_length=6)),
                ('img', models.ImageField(upload_to='img')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Beauty',
            },
        ),
        migrations.CreateModel(
            name='BeautyBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(default='NoWhere', max_length=33)),
                ('shape', models.CharField(default='Unknown', max_length=50)),
                ('age', models.CharField(default='Young', max_length=50)),
            ],
        ),
    ]
