# Generated by Django 2.1.1 on 2019-06-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_capsC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beauty',
            name='img',
            field=models.ImageField(upload_to='avatar'),
        ),
    ]
