# Generated by Django 3.1.3 on 2021-01-15 11:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model.fields
import model.store.model_user


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('username', models.CharField(max_length=16, verbose_name='账号')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('name', models.CharField(default='', max_length=32, verbose_name='姓名')),
                ('phone', models.CharField(default='', max_length=24, verbose_name='联系电话')),
                ('status', models.IntegerField(choices=[(0, 'Disable'), (1, 'Enable'), (2, 'Delete')], default=1, verbose_name='账号状态状态:DISABLE = 0 ENABLE = 1 DELETE = 2 [(ENABLE, 启用), (DISABLE, 停用), (DELETE, 删除)]')),
                ('last_login_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后一次登录时间')),
                ('is_main', models.BooleanField(default=False, verbose_name='是否为主账号')),
            ],
            options={
                'db_table': 'agent_account',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('name', models.CharField(default='', max_length=32, verbose_name='机构名称')),
                ('unique_id', models.CharField(default='', max_length=32, verbose_name='机构唯一标识符')),
                ('address', models.CharField(default='', max_length=50, verbose_name='机构地址')),
                ('phone', models.CharField(default='', max_length=32, verbose_name='机构电话')),
                ('login_url', models.CharField(default='', max_length=64, verbose_name='登录地址')),
                ('status', models.IntegerField(choices=[(0, 'Abnormal'), (1, 'Normal'), (2, 'Delete')], default=1, verbose_name='机构状态')),
            ],
            options={
                'db_table': 'agent_company',
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('type_desc', models.CharField(max_length=16, verbose_name='类别描述')),
                ('type', models.CharField(max_length=16, verbose_name='类别')),
                ('name', models.CharField(max_length=16, verbose_name='名称')),
                ('key', models.CharField(max_length=16, verbose_name='key')),
                ('value', models.CharField(default='', max_length=32, verbose_name='value')),
            ],
            options={
                'db_table': 'config',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('name', models.CharField(default='', max_length=24, verbose_name='表单名称')),
                ('is_limited', models.BooleanField(default=False, verbose_name='限填一次')),
                ('is_title_hide', models.BooleanField(default=True, verbose_name='是否隐藏表头')),
                ('unique_id', models.CharField(max_length=32, verbose_name='唯一标识符')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('url', models.CharField(default='', max_length=255, verbose_name='链接')),
                ('company', model.fields.VirtualForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_forms', to='model.company')),
            ],
            options={
                'db_table': 'agent_form',
            },
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('name', models.CharField(default='', max_length=24, verbose_name='投放页名称')),
                ('unique_id', models.CharField(max_length=32, verbose_name='唯一标识符')),
                ('url', models.CharField(default='', max_length=255, verbose_name='超链接')),
                ('status', models.IntegerField(choices=[(0, 'Unpublished'), (1, 'Published'), (2, 'Suspend'), (3, 'Delete')], default=0, verbose_name='发布状态: UNPUBLISHED = 0 PUBLISHED = 1 SUSPEND = 2 DELETE = 3 [(UNPUBLISHED, 未发布), (PUBLISHED, 投放中), (SUSPEND, 停止), (DELETE, 删除)]')),
                ('account', model.fields.VirtualForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_landing_pages', to='model.agentaccount')),
                ('company', model.fields.VirtualForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_landing_pages', to='model.company')),
            ],
            options={
                'db_table': 'agent_landing_page',
            },
        ),
        migrations.CreateModel(
            name='PlatformRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('name', models.CharField(default='', max_length=10, verbose_name='角色名称')),
                ('rules', models.JSONField(default=list, verbose_name='角色对应权限')),
                ('describe', models.CharField(default='', max_length=32, verbose_name='描述')),
                ('status', models.IntegerField(choices=[(0, 'Disable'), (1, 'Enable'), (2, 'Delete')], default=1, verbose_name='状态:DISABLE = 0 ENABLE = 1 DELETE = 2 [(ENABLE, 启用), (DISABLE, 停用), (DELETE, 删除)]')),
            ],
            options={
                'db_table': 'platform_role',
            },
        ),
        migrations.CreateModel(
            name='PlatformAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('username', models.CharField(max_length=16, verbose_name='账号')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('name', models.CharField(default='', max_length=32, verbose_name='姓名')),
                ('phone', models.CharField(default='', max_length=24, verbose_name='联系电话')),
                ('status', models.IntegerField(choices=[(0, 'Disable'), (1, 'Enable'), (2, 'Delete')], default=1, verbose_name='账号状态状态:DISABLE = 0 ENABLE = 1 DELETE = 2 [(ENABLE, 启用), (DISABLE, 停用), (DELETE, 删除)]')),
                ('last_login_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后一次登录时间')),
                ('is_main', models.BooleanField(default=False, verbose_name='是否为主账号')),
                ('role', model.fields.VirtualForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_platform_accounts', to='model.platformrole')),
            ],
            options={
                'db_table': 'platform_account',
            },
        ),
        migrations.CreateModel(
            name='LandingPageEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('remark', models.CharField(default='', max_length=250, verbose_name='备注')),
                ('action', models.IntegerField(choices=[(0, 'Create'), (1, 'Delete'), (2, 'Publish'), (3, 'Suspend'), (4, 'Rename'), (5, 'Copy')], default=0, verbose_name='操作类型: CREATE = 0 DELETE = 1 PUBLISH = 2 SUSPEND = 3 [(CREATE, 创建), (DELETE, 删除), (PUBLISH, 发布), (SUSPEND, 停止)], (RENAME, 重命名), (COPY, 创建副本)')),
                ('account', model.fields.VirtualForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_landingpageevent', to='model.agentaccount')),
                ('landing_page', model.fields.VirtualForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='model.landingpage')),
            ],
            options={
                'db_table': 'agent_landing_page_event',
            },
        ),
        migrations.CreateModel(
            name='LandingPageComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('index', models.IntegerField(default=0, verbose_name='序位')),
                ('name', models.CharField(default='', max_length=32, verbose_name='组件名称')),
                ('c_type', models.IntegerField(choices=[(0, 'Pic'), (1, 'Btn'), (2, 'Slid'), (3, 'Form')], default=0, verbose_name='组件类型: PIC = 0 BTN = 1 SLID = 2 FORM = 3 [(PIC, 图片), (BTN, 按钮), (SLID, 轮播), (FORM, 表单)]')),
                ('attrs', models.JSONField(default=dict, verbose_name='组件属性')),
                ('landing_page', model.fields.VirtualForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landing_page_components', to='model.landingpage')),
            ],
            options={
                'db_table': 'agent_landing_page_component',
            },
        ),
        migrations.CreateModel(
            name='FormEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('remark', models.CharField(default='', max_length=250, verbose_name='备注')),
                ('action', models.IntegerField(choices=[(0, 'Create'), (1, 'Delete'), (2, 'Edit')], default=0, verbose_name='操作类型: CREATE = 0 DELETE = 1[(CREATE, 创建), (DELETE, 删除),')),
                ('account', model.fields.VirtualForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_formevent', to='model.agentaccount')),
                ('form', model.fields.VirtualForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='model.form')),
            ],
            options={
                'db_table': 'agent_form_event',
            },
        ),
        migrations.CreateModel(
            name='FormComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('name', models.CharField(default='', max_length=32, verbose_name='组件名称')),
                ('describe', models.CharField(default='', max_length=32, verbose_name='描述')),
                ('is_needed', models.BooleanField(default=True, verbose_name='是否必填')),
                ('index', models.IntegerField(default=0, verbose_name='序位')),
                ('tag', models.IntegerField(choices=[(0, 'Name'), (1, 'Phone'), (2, 'Age'), (3, 'Gender'), (4, 'Text'), (5, 'Position'), (6, 'Addr'), (7, 'Job'), (8, 'Department'), (9, 'Company'), (10, 'Web'), (11, 'Tel'), (12, 'Fax')], default=0, verbose_name='标识: NAME = 0 PHONE = 1 AGE = 2 GENDER = 3 TEXT = 4 RADIO = 5 ADDRESS = 6 CHECKBOX = 7[(NAME, 姓名), (PHONE, 手机), (AGE, 年龄), (GENDER, 性别), (TEXT, 文本), (RADIO, 单选), (ADDRESS, 地址), (CHECKBOX, 多选)]')),
                ('c_type', models.IntegerField(choices=[(1, 'Text'), (2, 'Radio'), (3, 'Address'), (4, 'Checkbox')], default=1, verbose_name='组件类型: [(TEXT, 文本, 1), (RADIO, 单选, 2), (ADDRESS, 地址, 3), (CHECKBOX, 多选, 4)]')),
                ('attrs', models.JSONField(default=dict, verbose_name='组件属性')),
                ('form', model.fields.VirtualForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_components', to='model.form')),
            ],
            options={
                'db_table': 'agent_form_component',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('identity', models.CharField(default='', max_length=18, verbose_name='身份证号')),
                ('name', models.CharField(default='', max_length=32, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('man', '男士'), ('woman', '女士'), ('unknown', '未知')], default='unknown', max_length=8, verbose_name='性别')),
                ('birthday', models.DateField(default=model.store.model_user.default_date, verbose_name='生日')),
                ('phone', models.CharField(default='', max_length=16, verbose_name='手机号')),
                ('email', models.CharField(default='', max_length=64, verbose_name='邮箱')),
                ('city', models.CharField(default='', max_length=32, verbose_name='城市')),
                ('address', models.CharField(default='', max_length=64, verbose_name='详细地址')),
                ('remark', models.CharField(default='', max_length=64, verbose_name='备注')),
                ('company', model.fields.VirtualForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_customers', to='model.company')),
                ('form', model.fields.VirtualForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_customers', to='model.form')),
                ('landing_page', model.fields.VirtualForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landing_page_customers', to='model.landingpage')),
            ],
            options={
                'db_table': 'agent_customer',
            },
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('detail_data', models.JSONField(default=dict, verbose_name='提交信息详情')),
                ('is_valid', models.BooleanField(default=True, verbose_name='数据有效性')),
                ('remark', models.CharField(default='', max_length=64, verbose_name='备注')),
                ('customer', model.fields.VirtualForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_collections', to='model.customer')),
            ],
            options={
                'db_table': 'agent_collection',
            },
        ),
        migrations.CreateModel(
            name='AgentRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('name', models.CharField(default='', max_length=10, verbose_name='角色名称')),
                ('rules', models.JSONField(default=list, verbose_name='角色对应权限')),
                ('describe', models.CharField(default='', max_length=32, verbose_name='描述')),
                ('status', models.IntegerField(choices=[(0, 'Disable'), (1, 'Enable'), (2, 'Delete')], default=1, verbose_name='状态:DISABLE = 0 ENABLE = 1 DELETE = 2 [(ENABLE, 启用), (DISABLE, 停用), (DELETE, 删除)]')),
                ('company', model.fields.VirtualForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_roles', to='model.company')),
            ],
            options={
                'db_table': 'agent_role',
            },
        ),
        migrations.AddField(
            model_name='agentaccount',
            name='company',
            field=model.fields.VirtualForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_accounts', to='model.company'),
        ),
        migrations.AddField(
            model_name='agentaccount',
            name='role',
            field=model.fields.VirtualForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_agent_accounts', to='model.agentrole'),
        ),
    ]
