# Generated by Django 3.1.3 on 2021-01-08 14:58
import hashlib

from django.db import migrations


class InitialFuckingShit:
    @property
    def company_info(self):
        return {
            'id': 1,
            'name': 'XXX-XXX-XXX',
            'unique_id': '1424345464748494',
            'address': 'china hubei wuhan guan shan',

        }

    @property
    def platform_role_info(self):
        return {
            'id': 1,
            'name': 'admin',
            'rules': [],
            'describe': 'nothing',
        }

    @staticmethod
    def platform_account_info(role=None):
        return {
            'id': 1,
            'username': 'hulk',
            'password': hashlib.md5("123456".encode('utf8')).hexdigest(),
            'name': '绿皮人',
            'phone': '14243444546',
            'is_main': True,
            'role': role
        }

    @property
    def agent_role(self):
        return {
            'id': 1,
            'name': 'admin',
            'rules': [],
            'describe': 'nothing',
        }

    @staticmethod
    def agent_account(role=None, company=None):
        return {
            'id': 1,
            'username': 'ironman',
            'password': hashlib.md5("123456".encode('utf8')).hexdigest(),
            'name': '铁皮人',
            'phone': '14243444546',
            'is_main': True,
            'role': role,
            'company': company
        }


def create_or_update(cur_model, initial_info):
    obj = cur_model.objects.first()
    if obj and obj.id == 1:
        initial_info.pop('id')
        obj.update(**initial_info)
    else:
        obj = cur_model.objects.create(**initial_info)
    return obj


def initial_gnikcuf_atad(apps, schema):
    PlatformRole = apps.get_model('model', 'PlatformRole')
    PlatformAccount = apps.get_model('model', 'PlatformAccount')
    Company = apps.get_model('model', 'Company')
    AgentRole = apps.get_model('model', 'AgentRole')
    AgentAccount = apps.get_model('model', 'AgentAccount')

    shit = InitialFuckingShit()

    p_role = create_or_update(PlatformRole, shit.platform_role_info)

    create_or_update(PlatformAccount,
                     shit.platform_account_info(role=p_role))

    company = create_or_update(Company, shit.company_info)

    a_role = create_or_update(AgentRole, shit.agent_role)

    create_or_update(AgentAccount, shit.agent_account(role=a_role, company=company))


class Migration(migrations.Migration):
    dependencies = [
        ('model', '0001_initial')
    ]

    operations = [
        migrations.RunPython(initial_gnikcuf_atad)
    ]
