# Generated by Django 3.1.3 on 2021-01-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial_gnikcuf_atad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentaccount',
            name='username',
            field=models.CharField(max_length=32, verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='agentrole',
            name='name',
            field=models.CharField(default='', max_length=32, verbose_name='角色名称'),
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(default='', max_length=32, verbose_name='表单名称'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='name',
            field=models.CharField(default='', max_length=32, verbose_name='投放页名称'),
        ),
        migrations.AlterField(
            model_name='platformaccount',
            name='username',
            field=models.CharField(max_length=32, verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='platformrole',
            name='name',
            field=models.CharField(default='', max_length=32, verbose_name='角色名称'),
        ),
    ]
