# Generated by Django 3.1.3 on 2021-01-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20210118_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formcomponent',
            name='c_type',
            field=models.IntegerField(choices=[(1, 'Text'), (2, 'Radio'), (3, 'Address'), (4, 'Checkbox'), (5, 'Pics')], default=1, verbose_name='组件类型: [(TEXT, 文本, 1), (RADIO, 单选, 2), (ADDRESS, 地址, 3), (CHECKBOX, 多选, 4)]'),
        ),
        migrations.AlterField(
            model_name='formcomponent',
            name='tag',
            field=models.IntegerField(choices=[(0, 'Name'), (1, 'Phone'), (2, 'Age'), (3, 'Gender'), (4, 'Text'), (5, 'Position'), (6, 'Addr'), (7, 'Job'), (8, 'Department'), (9, 'Company'), (10, 'Web'), (11, 'Tel'), (12, 'Fax'), (13, 'Pics')], default=0, verbose_name='标识: NAME = 0 PHONE = 1 AGE = 2 GENDER = 3 TEXT = 4 RADIO = 5 ADDRESS = 6 CHECKBOX = 7[(NAME, 姓名), (PHONE, 手机), (AGE, 年龄), (GENDER, 性别), (TEXT, 文本), (RADIO, 单选), (ADDRESS, 地址), (CHECKBOX, 多选)]'),
        ),
    ]
