# Generated by Django 3.1.1 on 2020-09-06 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modify', models.DateTimeField(auto_now=True, verbose_name='last modify time')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='name')),
                ('phone', models.CharField(default='', max_length=14, verbose_name='phone')),
                ('password', models.CharField(max_length=32, verbose_name='password')),
                ('nickname', models.CharField(default='', max_length=64, verbose_name='nickname')),
                ('rank', models.CharField(choices=[('normal', '大众'), ('vip', '会员'), ('svip', '超级会员')], default='normal', max_length=16, verbose_name='rank')),
                ('friends', models.ManyToManyField(related_name='_userinfomodel_friends_+', to='user_info.UserInfoModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserDetailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modify', models.DateTimeField(auto_now=True, verbose_name='last modify time')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('age', models.IntegerField(default=0, verbose_name='nickname')),
                ('gender', models.CharField(choices=[('m', '官人'), ('f', '佳人'), ('u', '神人')], default='u', max_length=1, verbose_name='gender')),
                ('address', models.CharField(default='', max_length=256, verbose_name='address')),
                ('diploma', models.CharField(choices=[('primary', '幼稚园'), ('junior', '小学'), ('senior', '高中'), ('bachelor', '本科'), ('ma', '硕士'), ('ph.d', '博士'), ('professor', '教授'), ('ac', '院士'), ('other', '其他')], default='other', max_length=16, verbose_name='diploma')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_query_detail', to='user_info.userinfomodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modify', models.DateTimeField(auto_now=True, verbose_name='last modify time')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('interest', models.CharField(default='', max_length=64, unique=True, verbose_name='interest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_query_interest', related_query_name='interest_query_user', to='user_info.userinfomodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modify', models.DateTimeField(auto_now=True, verbose_name='last modify time')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('role', models.CharField(choices=[('normal', '普通用户'), ('manger', '管理员'), ('sectioner', '版主'), ('admin', '官方管理员')], default='normal', max_length=16, verbose_name='user role')),
                ('section', models.CharField(choices=[('none', '孤苦伶仃'), ('coding', '编程'), ('language', '语言'), ('history', '历史')], default='none', max_length=16, verbose_name='section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_query_role', related_query_name='role_query_user', to='user_info.userinfomodel')),
            ],
            options={
                'unique_together': {('user', 'role', 'section')},
            },
        ),
    ]
