# Generated by Django 2.2.5 on 2019-09-25 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restful', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64, verbose_name='Universally Unique Identifier')),
                ('name', models.CharField(max_length=256, verbose_name="plugin's name")),
                ('type', models.CharField(default='UNKNOWN', max_length=64, verbose_name='classify')),
                ('version', models.CharField(default='-', max_length=32, verbose_name='current version num')),
                ('size', models.CharField(max_length=16, verbose_name="plugins's size")),
                ('score', models.FloatField(default=3.0, verbose_name='user rating')),
                ('download', models.IntegerField(default=572, verbose_name='statistics of downloads')),
                ('my_download', models.IntegerField(default=129, verbose_name='statistics of my site downloads')),
                ('download_url', models.CharField(default='oops, the url is missing!', max_length=256, verbose_name='download url')),
                ('download_code', models.CharField(default='john', max_length=8, verbose_name='download code')),
                ('pics', models.ImageField(null=True, upload_to='plugins', verbose_name='pics about this plugin')),
                ('thumbnail', models.FilePathField(null=True, path='plugins/thumbnail', verbose_name='thumbnail path')),
                ('brief', models.TextField(default='very useful plugin', verbose_name='brief about plugin')),
                ('overview', models.TextField(default="sorry, no details! it's coming soon!", verbose_name='details about plugin')),
                ('url', models.CharField(default='-', max_length=256, verbose_name="plugin's url")),
                ('isvalid', models.BooleanField(default=True, verbose_name='valid or not')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create time')),
            ],
            options={
                'db_table': 'PluginsAlpha',
            },
        ),
    ]
