version: '3'

services:

  web:
    restart: always
    build: ./
    container_name: web
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=5(15ds+i2+%ik6z&!yer+ga9m=e%jcqiz_5wszg)r-z!2--b2d
      - DB_NAME=crm
      - DB_USER=root
      - DB_PASS=zxcde321TEST
      - DB_HOST=mysql
      - DB_PORT=3306
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_POOL_SIZE=500

    volumes:
      - /data/application/web/log:/var/log/app:Z
      - /data/application/web/private:/var/private:Z
      - /etc/localtime:/etc/localtime:Z
    external_links:
      - redis
      - mysql
    networks:
      - app_net
    command: /usr/local/bin/gunicorn wsgi:application -w 2 -b :8000

networks:
  app_net:
    external:
      name: oc_net
